<Project>

    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>

    <ItemGroup>
        <PackageVersion Include="BlazorStrap" Version="5.2.104" />
        <PackageVersion Include="BlazorStrap.V5" Version="5.2.104" />
        <PackageVersion Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="10.0.11" />
        <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
        <PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.11" />
        <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.11" />
        <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
        <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
        <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.11" />
        <PackageVersion Include="Microsoft.Extensions.Options" Version="10.0.11" />
        <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.10.0" />
        <PackageVersion Include="Microsoft.TypeScript.MSBuild" Version="2.3.3" />
        <PackageVersion Include="Microsoft.Web.LibraryManager.Build" Version="2.1.175" />
        <PackageVersion Include="Moq" Version="4.20.70" />
        <PackageVersion Include="MSTest.TestAdapter" Version="3.4.3" />
        <PackageVersion Include="MSTest.TestFramework" Version="3.4.3" />
        <PackageVersion Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageVersion Include="SixLabors.ImageSharp" Version="3.1.11" />
        <PackageVersion Include="SixLabors.ImageSharp.Drawing" Version="2.1.7" />
        <PackageVersion Include="System.CommandLine" Version="2.0.11" />
    </ItemGroup>

</Project>
